---

- hosts: all
  become: true
  tasks:

  - name: APT update cache & upgrade distribution
    tags: always, update, system
    apt:
      update_cache: yes
      upgrade: dist

  - name: Install system tools (snapd, git, curl, gparted, neofetch, jdk/jre)
    tags: system, dependencies
    apt:
      name:
        - snapd
        - git
        - curl
        - gparted
        - neofetch
        - default-jdk
        - default-jre
      state: latest

  - name: Install desktop clients (browsing, email, torrent)
    tags: desktop, web, mail, torrent
    apt:
      name:
        - firefox
        - thunderbird
        - thunderbird-locale-fr
        - thunderbird-locale-en
        - thunderbird-locale-en-gb
        - thunderbird-locale-en-us
        - transmission
        - telegram-desktop
      state: latest

  - name: Install Audacity & VLC
    tags: media
    apt:
      name:
        - audacity
        - vlc
      state: latest

  - name: Install text editors from snap with classic confinement
    tags: editor, snap, classic
    community.general.snap:
      name:
        - code
        - atom
        - sublime-text
      classic: yes

  - name: Install chatting softwares
    tags: chat, privacy
    apt:
      name:
        - telegram-desktop
      state: latest

  - name: Install Signal & WhatsApp from snap
    tags: chat, privacy, snap
    community.general.snap:
      name:
        - signal-desktop
        - whatsapp-for-linux

  - name: Install non-productive softwares from apt (Steam)
    tags: games, fun
    apt:
      name:
        - steam
      state: latest

  - name: Install non-productive softwares from snap (Discord & Spotify)
    tags: fun, music, games
    community.general.snap:
      name:
        - spotify
        - discord