---

- hosts: all
  become: true
  tasks:

    - name: Create "git" directory if it does not exist
      tags: always, folder, dependencies
      ansible.builtin.file:
        path: /home/m0ss/git
        state: directory
        mode: '0744'

    - name: Install OWASP ZAP proxy
      tags: offensive, proxy, websec
      community.general.snap:
        name:
          - zaproxy
        classic: yes

    - name: Install SQLmap
      tags: offensive, sqli, db
      community.general.snap:
        name:
          - zaproxy

    - name: Install offensive tools from apt
      tags: offensive, enumeration, network
      apt:
        name:
          - netcat
          - nmap
          - gobuster
        state: latest
