---

- hosts: all
  become: true
  tasks:

  - name: Update APT cache
    apt:
      update_cache: yes

  - name: Install system tools (snapd, git, curl, gparted, neofetch, jdk/jre)
    apt:
      name:
        - snapd
        - git
        - curl
        - gparted
        - neofetch
        - default-jdk
        - default-jre
      state: absent

  - name: Install desktop tools (firefox, thunderbird, vlc, )
    apt:
      name:
        - firefox
        - thunderbird
        - thunderbird-locale-fr
        - thunderbird-locale-en
        - thunderbird-locale-en-us
        - thunderbird-locale-en-uk
        - vlc
        - transmission
        - telegram-desktop
        - audacity
      state: absent

  - name: Install non-productive tools
    apt:
      name:
        - steam
      state: absent
