---

- hosts: all
  become: false
  tasks:

    - name: Create "git" directory if it does not exist
      tags: always, folder, dependencies
      ansible.builtin.file:
        path: /home/{{username}}/git
        state: directory
        mode: '0755'

    - name: Clone SecLists repo into git folder
      tags: offensive, wordlists, git
      ansible.builtin.git:
        repo: https://github.com/danielmiessler/SecLists
        dest: /home/{{username}}/git/SecLists

    - name: Clone John The Ripper repo into git folder
      tags: offensive, hash, git
      ansible.builtin.git:
        repo: https://github.com/openwall/john
        dest: /home/{{username}}/git/john

    - name: Install John The Ripper dependencies
      tags: always, hash, dependencies
      apt:
        name:
          - git
          - build-essential
          - libssl-dev
          - zlib1g-dev
          - yasm
          - pkg-config
          - libgmp-dev
          - libpcap-dev
          - libbz2-dev
        state: latest
      become: yes

    - name: Configure John The Ripper Makefile
      tags: offensive, hash, script
      ansible.builtin.shell:
      args:
        cmd: /bin/bash /home/{{username}}/git/john/src/configure > ansible_configure.log
        creates: Makefile
        chdir: /home/{{username}}/git/john/src/

    - name: Compile John The Ripper from source (make -s clean)
      tags: offensive, hash, make
      make:
        chdir: /home/{{username}}/git/john/src
        target: clean

    - name: Compile John The Ripper from source (make -sj4)
      tags: offensive, hash, make
      make:
        chdir: /home/{{username}}/git/john/src
        params:
            NUM_THREADS: 4

    - name: Clone PEASS-ng repo into git folder
      tags: offensive, escalation, git
      ansible.builtin.git:
        repo: https://github.com/carlospolop/PEASS-ng
        dest: /home/{{username}}/git/PEASS-ng

    - name: Clone hash-identifier repo into git folder
      tags: offensive, hash, git
      ansible.builtin.git:
        repo: https://github.com/blackploit/hash-identifier
        dest: /home/{{username}}/git/hash-identifier

    - name: Clone Responder repo into git folder
      tags: offensive, responder, git
      ansible.builtin.git:
        repo: https://github.com/lgandx/Responder
        dest: /home/{{username}}/git/Responder

